# Site settings
title: "Núria Belloc"
description_short: "Shiatsu a Gràcia"
description: > #
  El shiatsu és una eina de contacte entre persones,
  un procés en moviment i en continua evolució.

email: shiatsu.nbr@gmail.com
addr: "c/ Sors, nº 10. Gràcia"
address: "c/Sors nº 10, baixos 1ª (interior). Gràcia, Barcelona"
tel: (+34) 651 862 122

permalink: pretty
url: http://shiatsu.nuriabelloc.com
# sslurl: https://shiatsu.nuriabelloc.com
baseurl: '' # '/f3'
cdn: 'https://googledrive.com/host/0Bxwn2g3WSTbRfk1DVGpwbEl4dFA3ajFiTGFyZlA0WklGY3Izc0YtSHhVYncyVk01SzBibjQ'
analytics: 'UA-59689079-1'
timezone: Europe/Amsterdam
date: 2015-04-23 00:00:00 # for pages in feed.xml
# Build settings
markdown: kramdown
layouts_dir: _layouts
includes: _includes
exclude: [Gemfile, Gemfile.lock, Guardfile, todo.md]
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: css/_sass
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      lang: cat
  -
    scope:
      path: es
      type: "pages"
    values:
      layout: page
      lang: es

# Prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  ignore: ['_config.yml', '404.html', 'sitemap.xml', 'robots.txt', 'README.md', 'CNAME', '.gitignore', '.editorconfig', 'css', 'js','_layouts', '_includes', 'feed.xml', 'favicon.ico', 'todo.md']
  media: 'image'
  metadata:
    '':
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicat?"
          help: "Clickat apareixerà a la web"
          value: true
      - name: "menu"
        field:
          element: "checkbox"
          label: "vols que aparegui al menú de la web?"
          help: "si està clickat apareixerà al menú"
          value: boolean
      - name: "description"
        field:
          element: "text"
          label: "Descripció de la pàgina"
          help: "serveix per al google, quan busquin"
          placeholder: "Descriu amb una frase (o dos) els continguts de la pàgina"
      - name: "permalink"
        field:
          element: "text"
          label: "La ruta de la pagina"
          help: "s'ha d'escriure sense http://shiatsu.nuriabelloc.com/ i acabat amb /"
          placeholder: "exemple/"
          type: text
      - name: "sibling"
        field:
          element: "text"
          label: "Identifica les pagines (germanes) traduides"
          help: "La pàgina de contacte en català i castella tindran aquest camp igual"
          placeholder: "exemple"
          type: text
